sudo: required
services:
- docker
env:
  matrix:
  - TEST_SUITE=2.7
  - TEST_SUITE=3.6
  - TEST_SUITE=3.7
  global:
  - secure: R/zo0NJ7VanVi24r7p9CUqvwmlSGoQUsSa60xALg8J6wcR446eCY0ZcPYqbKcyuFFt9ejvQ+Avs3YhHBdZYcMzazWtM0DE1NnQgi9KShgQCROAnnsweOKW0CDavhXoVNErOxjgN8A1NeTo0JEcDRsPKg8NDfH/ugE3oBSs3N9wUEV3SjhOtO5Niwlf4f//Z2Dqy4iO0l922G0M595uCM2p22xVvMpYUhXphrSBuGXGj/E3vAcD12/9bIFGpPzHFZEa3hFjsIv97uybNM1nF6XlyoDUKgCVnLUT01/QhHa2XEtP5RaQddDH79LQh7I6LkzKDKhMIxLmo+Xs/HpcFb6cQ6pkwJXbPXe50P3Lt8QlwLhmPOvVaujYMuijOCT5ozdWGgM828gsBU0rqcNF8JBVwj2qkJZbgK1w3TP70/jikX16EELx4Qf9AnzGuIjifjDwopqzTobyFUBqkMYlvlp4cAbfQ3MwhU2OVFLwTUGlEkeeKkpu8yBjw4Tx34KXA625xaRetPSMTKqrPwW2Z9gbbv5gjbu8gCIZB7CiJZQ/zzVOhE1ijvjiXcZuxmD6FfXDpoUXIzqnl3UUkGVdj2VNa4sTUrTxj2H0X9T8XJcbKG8S+7o7r/eND4UnuL/zPuNSHUd3BP/fhaTuEftECxH/lubaSF+mUki3XO4Dqk3AE=
  - secure: KDGbDD9JqS9nyqWRG0C+EqMvtzBfOTKpwLGlHArROSY2nIxnbhxwuRyUYFafmC1MI0Y4d4tyUIoOGADVcZ4unLn20U6AjFBi/PdWCoCIiYSHIJ8R34UzNSWjeNlx1Suwk0POEr/9Rmh3jGDdrqq73IM4cO16DDhymAsVkRFvwErcH2krZqRwpB5tVEMulw7ndwWopZ+Ojrq6m/CDCI+9DYq78sppCQtVAdstLpSl4esjHPdl2XjDimAMzNNw4W5aht7oa99c68pMeja4v/uRkN1jGRHJ3gXQjDnnDGeiGJzbhUXbUmlNpB1c7DuEh+iArZRVWdsKtL0OZf03sLkqQLEXFCVTBRBckIpLemoOKX5wa3/7FstEWloUOv5Mb5LlE7yuoYeEPqLxHIUfItoAY2hVw5R+TZ3LjiJdT+fyzBvpdFrUmuuPaJhwHCdtjrd93Q5lg3enWXLvWGyvhrE/TvX0x9ljm5V4ptne5MOvMvR2mbMOOZaSGn5X1RQ+wWOW3+9XxRx8KZ7n6FUUtpjCqrw89v8qU8QeN1vfshIYCDshFuZcpqlOTod/7+mznKBl5QbCJnXZMaSK6IZzkhlVCl9qcQ1vNtjkVa+1x8b6tw9vk/pP1M6nrJIP4y09rL0UfMujoQBIWt4CvPcasCvTdtfn5jz0aufdNrVHYOCtkkQ=

script:
- docker build --build-arg PYTHON_VERSION=${TEST_SUITE} -t iamjohnnym/bionic-python:${TEST_SUITE} .
after_success:
- echo "${DOCKER_PASSWORD}" | docker login --username="${DOCKER_USER}" --password-stdin
- if [[ ${TRAVIS_PULL_REQUEST} == "false" ]] && [[ ${TRAVIS_BRANCH} == "master" ]];
  then
    docker push iamjohnnym/bionic-python;
  fi
